#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-etuples
Version  : 0.3.3
Release  : 1
URL      : https://files.pythonhosted.org/packages/92/37/04812c0637d6208c3de9a65380609411842b093eee6377dc7edfa6009920/etuples-0.3.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/92/37/04812c0637d6208c3de9a65380609411842b093eee6377dc7edfa6009920/etuples-0.3.3.tar.gz
Summary  : Python S-expression emulation using tuple-like objects.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-etuples-license = %{version}-%{release}
Requires: pypi-etuples-python = %{version}-%{release}
Requires: pypi-etuples-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cons)
BuildRequires : pypi(multipledispatch)

%description
# `etuples`
[![Build Status](https://travis-ci.org/pythological/etuples.svg?branch=master)](https://travis-ci.org/pythological/etuples) [![Coverage Status](https://coveralls.io/repos/github/pythological/etuples/badge.svg?branch=master)](https://coveralls.io/github/pythological/etuples?branch=master) [![PyPI](https://img.shields.io/pypi/v/etuples)](https://pypi.org/project/etuples/)

%package license
Summary: license components for the pypi-etuples package.
Group: Default

%description license
license components for the pypi-etuples package.


%package python
Summary: python components for the pypi-etuples package.
Group: Default
Requires: pypi-etuples-python3 = %{version}-%{release}

%description python
python components for the pypi-etuples package.


%package python3
Summary: python3 components for the pypi-etuples package.
Group: Default
Requires: python3-core
Provides: pypi(etuples)
Requires: pypi(cons)
Requires: pypi(multipledispatch)

%description python3
python3 components for the pypi-etuples package.


%prep
%setup -q -n etuples-0.3.3
cd %{_builddir}/etuples-0.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1640116621
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-etuples
cp %{_builddir}/etuples-0.3.3/LICENSE %{buildroot}/usr/share/package-licenses/pypi-etuples/7bd5743dd22a2d17c5f0ac816ba882247cc025ce
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-etuples/7bd5743dd22a2d17c5f0ac816ba882247cc025ce

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
